services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Rbac_Dev_Passw0rd!"
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "Rbac_Dev_Passw0rd!" -Q "SELECT 1" || exit 1
      interval: 10s
      retries: 10
